name: Deploy to VPS

on:
  push:
    branches:
      - live
  workflow_dispatch:

jobs:
  build-and-deploy-backend:
    name: Build & Deploy Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install & Test Backend
        working-directory: backend
        run: |
          npm ci
          npm test

      - name: SSH & Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git config --global --add safe.directory /var/www/sharpai/backend
            cd /var/www/sharpai/backend
            git fetch --all --prune
            git reset --hard origin/live
            sudo rm -rf node_modules
            sudo npm ci --production --unsafe-perm
            sudo mkdir -p /home/deploy/.pm2/{logs,pids}
            sudo chown -R deploy:deploy /home/deploy/.pm2
            sudo pm2 reload sharpai-backend --update-env \
              || sudo pm2 start index.js --name sharpai-backend --instances max --exec_mode cluster --update-env
            sudo pm2 save

  build-and-deploy-frontend:
    name: Build & Deploy Frontend
    needs: build-and-deploy-backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      - name: Sync Frontend to VPS
        uses: appleboy/scp-action@master
        with:
          host:     ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          source:   "frontend/dist/*"
          target:   "/var/www/sharpai/frontend/dist"

      - name: Fix Permissions & Reload Nginx
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key:      ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo chown -R www-data:www-data /var/www/sharpai/frontend/dist
            sudo nginx -t && sudo systemctl reload nginx
