name: Deploy to VPS (password SSH)

on:
  push:
    branches:
      - live
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Get your code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2) Build & test backend
      - name: Setup Node.js for Backend
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install & Test Backend
        working-directory: backend
        run: |
          npm ci
          npm test

      # 3) Deploy backend via SSH (password)
      - name: SSH & Deploy Backend
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASS }}
          port:     22
          script: |
            cd /var/www/sharpai/backend

            # prevent "dubious ownership" without writing to /root/.gitconfig
            git config --local --add safe.directory /var/www/sharpai/backend

            git fetch --all --prune
            git reset --hard origin/live

            rm -rf node_modules
            npm ci --production --unsafe-perm

            # reload (or start) under PM2
            pm2 reload sharpai-backend --update-env \
              || pm2 start index.js --name sharpai-backend --instances max --exec_mode cluster --update-env

            pm2 save

      # 4) Build frontend
      - name: Setup Node.js for Frontend
        uses: actions/setup-node@v3
        with:
          node-version: '20'
      - name: Install & Build Frontend
        working-directory: frontend
        run: |
          npm ci
          npm run build

      # 5) Copy dist/ up via SCP (password)
      - name: Copy Frontend dist to VPS
        uses: appleboy/scp-action@master
        with:
          host:     ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASS }}
          port:     22
          source:   "frontend/dist/*"
          target:   "/var/www/sharpai/frontend/dist"

      # 6) Fix permissions & reload Nginx
      - name: Fix perms & reload Nginx
        uses: appleboy/ssh-action@master
        with:
          host:     ${{ secrets.REMOTE_HOST }}
          username: root
          password: ${{ secrets.REMOTE_PASS }}
          port:     22
          script: |
            chown -R www-data:www-data /var/www/sharpai/frontend/dist
            nginx -t && systemctl reload nginx
